name = "buffon"
version = "0.1.0"
license = "license"
author = "fortran66"
maintainer = "fortran667795@gmail.com"
copyright = "Copyright 2023, fortran66"
[build]
auto-executables = true
auto-tests = true
auto-examples = true
[install]
library = false
